name: Compile Release
on:
  release:
    types: [published]

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          ref: ${{ github.event.release.tag_name }}

      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "latest"
          enable-cache: false

      - name: Install PlatformIO Core
        run: uv pip install --system -U https://github.com/pioarduino/platformio-core/archive/refs/tags/v6.1.19.zip

      - name: Build CrossPoint
        run: pio run -e gh_release

      - name: Patch min_chip_rev_full to 0
        run: python3 scripts/patch_min_chip_rev.py .pio/build/gh_release/firmware.bin

      - name: Upload bootloader.bin to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: .pio/build/gh_release/bootloader.bin
          asset_name: bootloader.bin
          content_type: application/octet-stream

      - name: Upload firmware.bin to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: .pio/build/gh_release/firmware.bin
          asset_name: firmware.bin
          content_type: application/octet-stream

      - name: Upload firmware.elf to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: .pio/build/gh_release/firmware.elf
          asset_name: firmware.elf
          content_type: application/octet-stream

      - name: Upload firmware.map to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: .pio/build/gh_release/firmware.map
          asset_name: firmware.map
          content_type: application/octet-stream

      - name: Upload partitions.bin to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: .pio/build/gh_release/partitions.bin
          asset_name: partitions.bin
          content_type: application/octet-stream
